# -*- coding: utf-8 -*-
# TN_title_mapping.py - Team Nitro
# خريطة تحويل الأسماء من الفرانكو/عربي إلى إنجليزي

TITLE_MAPPING = {
    # أفلام
    "بلود دايموند": "Blood Diamond",
    "ميستك ريفر": "Mystic River",
    "ديسبرتلي سيكينغ سوزان": "Desperately Seeking Susan",
    "كثيب": "Dune",
    "كثيب: الجزء الثاني": "Dune: Part Two",
    "ديون: الجزء الثاني": "Dune: Part Two",
    "Last Vegas - Despedida De Arromba": "Last Vegas",
    "Mulherzinhas (2019)": "Little Women",
    "Tubarão 3": "Jaws 3",
    "Shahr Al Asal": "Honeymoon",
    "Taht Al Tahded": "Under Threat",
    "Vrasës me pagesë": "The Mechanic",
    "Teyoor El Zalaam": "The Dark Tower",
    "UNFAITHFUL": "Unfaithful",
    "Heaven in Hell": "Heaven in Hell",
    "Despite The Falling Snow": "Despite the Falling Snow",
    "Legacy of Lies": "Legacy of Lies",
    "La morte vivante": "The Living Dead",
    "Mohamed Hussein": "Mohamed Hussein",
    "Salma": "Salma",
    "Soupcons The Staircase": "The Staircase",
    "Love & Marriage: Detroit": "Love & Marriage: Detroit",
    "Juniors": "Juniors",
    "Max Manus": "Max Manus",
    "Sanctum": "Sanctum",
    "Nereden Nereye": "Nereden Nereye",
    "Little Men": "Little Men",
    "A Fúria De Becky": "We're the Millers",
    "A Última Amante": "The Last Mistress",
    "A Lista dos Ex": "The Ex List",
    "Ostatnia szansa ludzkości": "The Last Chance for Humanity",
    "Les confins du monde": "The Edge of the World",
    "La morsure": "The Bite",
    "Crimes en série": "Serial Crimes",
    "Romulus et Remus": "Romulus and Remus",

    # مسلسلات
    "السيد ابو العربي وصل": "Al Sayed Abo El Arabi Wasel",
    "لالي": "Layali Eugenie",
    "شـرّفتونا": "Shurtoona",
    "هي ودافنشي": "She and Da Vinci",
    "مجاريح": "Majareeh",
    "إمبراطورية ميم": "Empire of Mim",
    "إل كبيير عوي": "El Kabeer Awy",
    "الخلاصة": "Al Kholasa",
    "سي بي سي دراما": "CBC Drama",
    "أفراح القبة": "Afrah Al Koba",
    "تاتش": "Touch",
    "عميلة سرية": "Secret Agent",
    "ذا ليغو موڤي 2: ذا سيكند بارت": "The Lego Movie 2: The Second Part",
    "ذَا ليغو موڤي 2: ذَا سيكند بارت": "The Lego Movie 2: The Second Part",
    "Life": "Life",
    "In the Name of Love": "In the Name of Love",
    "الحياة مسلسلات - برنامج أفلام ومسلسلات عربية": "NO_IMAGE",
    "فات الميعاد": "Missed the Deadline",
    "حكايات بنات": "Girls' Stories",
    "90 دقيقة": "90 Minutes",
    "في مواجهة الحب": "Facing Love",
    "إشق إداريان": "Ishq Edariyan",
    "ساند كي آنكه": "Sandeep Aur Pinky Faraar",
    "مات هاتر كرونيكلز: ألاينس أوف إيفل": "Mortal Kombat: Legacy",
    "إن ايه مانز وورلد: صابرينا": "In a Man's World: Sabrina",
    "Orman Dostlarõ 1-2-3-5": "Forest Friends",
    "Zaklinacze koni 7: odc.18": "Horse Whisperer 7: Ep.18",
    "Panda: odc.3": "Panda: Ep.3",
    "Castle 5: odc.15": "Castle 5: Ep.15",
    "Boks: BKB 34 w Londynie": "Boxing: BKB 34 in London",
    "O Meu Nome é Farah (Tur) T1 - Ep. 78": "My Name is Farah (Turkish) S1 - Ep.78",
    "Os Mistérios De Pearl T1 - Ep. 4": "The Mysteries of Pearl S1 - Ep.4",
}

# أسماء يجب تجاهلها (لا تبحث عنها)
NO_IMAGE_NAMES = [
    "قناة تجريبية",
    "Broadcasts Will Resume Soon",
    "Zakończenie programu",
    "Domek na prerii 4",
    "الحياة مسلسلات - برنامج أفلام ومسلسلات عربية",
    "INFO - WCIŚNIJ PRZYCISK 'I' LUB 'EPG'",
    "Newsflash SRF zwei",
    "Sur les Docs",
    "Les classiques du cinéma",
    "Ya Masaa El Anwar",
    "Ana Bint Abi",
]