# -*- coding: utf-8 -*-
TITLE_MAPPING = {
    "السيد ابو العربي وصل": "Al Sayed Abo El Arabi Wasel",
    "شـرّفتونا": "Shurtoona",
    "ذا ليغو موڤي 2: ذا سيكند بارت": "The Lego Movie 2: The Second Part",
    "Life": "Life",
    "In the Name of Love": "In the Name of Love",
    "الحياة مسلسلات - برنامج أفلام ومسلسلات عربية": "NO_IMAGE",
    "Last Vegas - Despedida De Arromba": "Last Vegas",
    "Mulherzinhas (2019)": "Little Women",
    "Tubarão 3": "Jaws 3",
    "Shahr Al Asal": "Honeymoon",
    "Taht Al Tahded": "Under Threat",
    "Vrasës me pagesë": "The Mechanic",
    "Teyoor El Zalaam": "The Dark Tower",
    "UNFAITHFUL": "Unfaithful",
    "Heaven in Hell": "Heaven in Hell",
    "Despite The Falling Snow": "Despite the Falling Snow",
    "Legacy of Lies": "Legacy of Lies",
    "La morte vivante": "The Living Dead",
    "Mohamed Hussein": "Mohamed Hussein",
    "Salma": "Salma",
    "Soupcons The Staircase": "The Staircase",
    "Love & Marriage: Detroit": "Love & Marriage: Detroit",
    "Juniors": "Juniors",
    "Max Manus": "Max Manus",
    "Sanctum": "Sanctum",
    "Nereden Nereye": "Nereden Nereye",
    "Little Men": "Little Men",
    "A Fúria De Becky": "We're the Millers",
    "A Última Amante": "The Last Mistress",
    "A Lista dos Ex": "The Ex List",
    "Ostatnia szansa ludzkości": "The Last Chance for Humanity",
    "Les confins du monde": "The Edge of the World",
    "La morsure": "The Bite",
    "Crimes en série": "Serial Crimes",
    "Romulus et Remus": "Romulus and Remus",
}

NO_IMAGE_NAMES = [
    "قناة تجريبية",
    "Broadcasts Will Resume Soon",
    "Zakończenie programu",
    "Domek na prerii 4",
    "الحياة مسلسلات - برنامج أفلام ومسلسلات عربية",
    "INFO - WCIŚNIJ PRZYCISK 'I' LUB 'EPG'",
    "Newsflash SRF zwei",
    "Sur les Docs",
    "Les classiques du cinéma",
    "Ya Masaa El Anwar",
    "Ana Bint Abi",
]