# -*- coding: utf-8 -*-
# TN_title_mapping.py - Team Nitro
# خريطة تحويل الأسماء من العربي/الفرانكو إلى الإنجليزي

TITLE_MAPPING = {
    # أفلام
    "Last Vegas - Despedida De Arromba": "Last Vegas",
    "Tubarão 3": "Jaws 3",
    "Mulherzinhas (2019)": "Little Women",
    "Shahr Al Asal": "Honeymoon",
    "Taht Al Tahded": "Under Threat",
    "Dune: الجزء الثاني": "Dune: Part Two",
    "كثيب: الجزء الثاني": "Dune: Part Two",
    "ديون: الجزء الثاني": "Dune: Part Two",
    "Vrasës me pagesë": "The Mechanic",
    "Teyoor El Zalaam": "The Dark Tower",
    "Broadcasts Will Resume Soon": "NO_IMAGE",
    "Zakończenie programu": "NO_IMAGE",
    "قناة تجريبية": "NO_IMAGE",
    "Domek na prerii 4": "NO_IMAGE",
    "UNFAITHFUL": "Unfaithful",
    "Heaven in Hell": "Heaven in Hell",
    "Despite The Falling Snow": "Despite the Falling Snow",
    "Legacy of Lies": "Legacy of Lies",
    "La morte vivante": "The Living Dead",
    "Mohamed Hussein": "Mohamed Hussein",
    "Salma": "Salma",
    "Soupcons The Staircase": "The Staircase",
    "Love & Marriage: Detroit": "Love & Marriage: Detroit",
    "Juniors": "Juniors",
    "Max Manus": "Max Manus",
    "Sanctum": "Sanctum",
    "Nereden Nereye": "Nereden Nereye",
    "Little Men": "Little Men",

    # مسلسلات
    "السيد ابو العربي وصل": "Al Sayed Abo El Arabi Wasel",
    "لالي": "Layali Eugenie",
    "شـرّفتونا": "Shurtoona",
    "هي ودافنشي": "She and Da Vinci",
    "مجاريح": "Majareeh",
    "إمبراطورية ميم": "Empire of Mim",
    "إل كبيير عوي": "El Kabeer Awy",
    "الخلاصة": "Al Kholasa",
    "سي بي سي دراما": "CBC Drama",
    "أفراح القبة": "Afrah Al Koba",
    "تاتش": "Touch",
    "عميلة سرية": "Secret Agent",
    "ذا ليغو موڤي 2: ذا سيكند بارت": "The Lego Movie 2: The Second Part",
    "ذَا ليغو موڤي 2: ذَا سيكند بارت": "The Lego Movie 2: The Second Part",
    "Life": "Life",
    "In the Name of Love": "In the Name of Love",
    "الحياة مسلسلات - برنامج أفلام ومسلسلات عربية": "NO_IMAGE",
    "فات الميعاد": "Missed the Deadline",
    "حكايات بنات": "Girls' Stories",
    "90 دقيقة": "90 Minutes",
    "في مواجهة الحب": "Facing Love",
    "إشق إداريان": "Ishq Edariyan",
    "ساند كي آنكه": "Sandeep Aur Pinky Faraar",
    "مات هاتر كرونيكلز: ألاينس أوف إيفل": "Mortal Kombat: Legacy",
    "إن ايه مانز وورلد: صابرينا": "In a Man's World: Sabrina",
}

# أسماء يجب تجاهلها (لا تبحث عنها)
NO_IMAGE_NAMES = [
    "قناة تجريبية",
    "Broadcasts Will Resume Soon",
    "Zakończenie programu",
    "Domek na prerii 4",
]